### PR TITLE
Initial database design commit

### PR DESCRIPTION
**Pull request by eddiecjc**
Work in progress, initial commit.

### CODE REVIEW

**Comment by ayroblu** [comment]
What do you use to view this xml file?

**Comment by eddiecjc** [comment]
SQL Power Architect, the Community Edition will do.
http://www.sqlpower.ca/page/architect_download_os


Cheers,
Eddie

**Comment by ayroblu** [comment]
I've pushed my thoughts on the sql to dbdesign branch. I think the main things were that the categories/tags are the same thing, and each poi only has one, so the extra tables for those are probably unnecessary (not 100% about that, but it looks like it). Other thing is that I've used a lower case tablenames convention, it seems to be a somewhat common convention so meh. Otherwise, you were missing some id fields etc, no big deal, actual sql code written

**Comment by eddiecjc** [comment]
Thanks Ben.
I am having problem pulling request from either master branch or the
dbdesign branch from OpenCityProject/ocp-docker, I got "verification
failed" every time I tried, so I could only fork it into a branch under my
own account.
Do you know if there is some steps I am missing?


Cheers,
Eddie

**Comment by ayroblu** [comment]
I'm not sure I understand your issue, cloning/pulling from a public repo in github is the same and open to all accounts.
If you're having issues authing with github, perhaps using the https link as the remote might work?
Post up your error?

**Pull request closed without merging**
